sudo: required
dist: trusty
language: python

python:
 - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc texlive lmodern texlive-lang-german

script: make

notifications:
  irc: "irc.freenode.org#oparl"
